# Site settings

title: Adi Riley Artist # Title of your site
email: adirileyartist@outlook.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Professional illustrator.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://adirileyartist.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     AdiRileyArtist
github_username:        # Replace this with your GitHub username
linkedin_username:      # Replace this with your LinkedIn username
google_plus_username:   # Replace this with your Google+ username
facebook_username:    adirileyartist  # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username
patreon_username:     adirileyartist
etsy_username:        AdiRileyArtist
instagram_username:   adirileyartist
tumblr_username:      adirileyartist
pinterest_username:   adirileyartist

# Build settings
markdown: kramdown
